logging:
  level:
    ROOT: INFO

spring:
  # 在线诊断
  arthas:
    enabled: false
  # 缓存数据库
  redis:
    enabled: false
    password:
    timeout: 5000
    database: 1
    host: localhost
    port: 6379
  # 链路跟踪
  zipkin:
    base-url: http://localhost:9411
  # 链路采集
  kafka:
    bootstrap-servers: localhost:9092

# 实时监控
cat:
  enabled: false
  home: /tmp
  servers: localhost
  tcp-port: 2280
  http-port: 8080
