logging:
  config: classpath:log4j2.yml

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript
    min-response-size: 1024

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      refresh-routes:
        enabled: true
        nacos:
          enabled: true
          data-id: gateway-routes.json
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    time-zone: GMT+8
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    mode: HTML
    cache: true
  sleuth:
    sampler:
      probability: 1.0
      rate: 10000
    propagation:
      tag:
        enabled: true
        whitelisted-keys:
          - stress # 压测标识
    propagation-keys:
      - stress
    web:
      enabled: true
    async:
      configurer:
        enabled: false # Bugfix：与 Spring 高版本存在冲突
  zipkin:
    discovery-client-enabled: true
    locator:
      discovery:
        enabled: true
  arthas:
    enabled: false

# Arthas
arthas:
  agent-id: ${spring.application.name}@${random.value}
  tunnel-server: ws://127.0.0.1:7777/ws
  session-timeout: 1800
  telnet-port: 0
  http-port: 0
