logging:
  level:
    ROOT: INFO
    org.ylzl.eden: DEBUG
    org.ylzl.eden.gateway.infrastructure: DEBUG

spring:
  # 在线诊断
  arthas:
    enabled: true
  # 缓存数据库
  redis:
    #    database: 1
    #    host: localhost
    #    port: 6379
    password: puyiwm
    timeout: 5000
    cluster:
      nodes: 10.2.2.45:6379,10.2.2.48:6379,10.2.2.47:6379,10.2.2.47:6380,10.2.2.47:6381,10.2.2.47:6382
  # 模板引擎
  thymeleaf:
    cache: false
  # 链路跟踪
  zipkin:
    base-url: http://10.2.2.47:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin
  # 链路采集
  kafka:
    bootstrap-servers: 10.2.2.35:9092
    producer:
      batch-size: 4096
      buffer-memory: 40960
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 实时监控
cat:
  enabled: true
  home: /tmp
  servers: 127.0.0.1
  tcp-port: 2280
  http-port: 8080
